### PR TITLE
Added netcoreapp2.0 target

### PR DESCRIPTION
**Pull request by ncave**
@enricosada or @cloudRoutine Please review, thanks in advance.

### CODE REVIEW

**Comment by ncave** [comment]
@enricosada @cloudRoutine I sincerely apologize for the bump, please let me know if I can help to move this along.

**Comment by enricosada** [comment]
i missed that, sry @ncave .
I'll release tomorrow a package

**Comment by ncave** [comment]
@enricosada Thanks, I appreciate your help!

**Comment by ncave** [comment]
@enricosada Thanks for merging, hopefully this can be published so we can drop the netcore 1.0 dependency.

**Comment by ncave** [comment]
Thanks @enricosada, let me know if I can help in any way to get this published.

**Pull request merged**
